/**
 * From tokens to the files a project imports.
 *
 *   css           @layer theme { :root { --color-bg: …; } } for any stack
 *   tailwind      the same values as a Tailwind v4 @theme block
 *   claudeDesign  the list-shaped tokens.json a Claude Design System reads
 *
 * Themes: the base files are the first theme ("light"). Each extra theme lists
 * files that override colours only; a colour that differs is emitted as
 * light-dark(), so one :root carries both and `color-scheme` (or
 * data-theme="…") picks. Anything else differing per theme is an error: a
 * dark mode with a different spacing scale is a second design system.
 */
import { flatten, loadTree, resolve, aliasOf, toHex, NS } from './tokens.mjs';
import { ROLES } from './contract.mjs';

export const GENERATED_BANNER = 'Generated by @mickaelbeauregard/design-system — do not edit. Run `ds build`.';

/** The viewport range a fluid size travels across, in px. Below the first it
 *  sits at its phone size; above the second, at its max. */
export const FLUID_RANGE = [360, 1280];

export function loadSystem(config) {
  const themeNames = ['light', ...Object.keys(config.themes ?? {})];
  if (themeNames.length > 2) {
    /* light-dark() takes exactly two. A third theme needs [data-theme] blocks,
       which no project has asked for yet. */
    return { errors: ['themes: at most one extra theme ("dark"); light-dark() takes two values'] };
  }
  const errors = [];
  const themes = {};
  for (const theme of themeNames) {
    const files = theme === 'light' ? config.tokenFiles : [...config.tokenFiles, ...config.themes[theme]];
    let loaded;
    try {
      loaded = loadTree(files);
    } catch (err) {
      return { errors: [err.message] };
    }
    const { tokens, errors: flatErrors } = flatten(loaded);
    const { resolved, errors: resolveErrors } = resolve(tokens);
    errors.push(...[...flatErrors, ...resolveErrors].map((e) => (theme === 'light' ? e : `[${theme}] ${e}`)));
    themes[theme] = { tokens, resolved };
  }
  if (errors.length) return { errors: [...new Set(errors)] };

  const base = themes.light;
  for (const [name, theme] of Object.entries(themes)) {
    if (name === 'light') continue;
    for (const [path, token] of theme.tokens) {
      const baseToken = base.tokens.get(path);
      if (!baseToken) errors.push(`[${name}] ${path}: a theme overrides tokens, it cannot add one`);
      else if (token.type !== 'color' && JSON.stringify(token.raw) !== JSON.stringify(baseToken.raw)) {
        errors.push(`[${name}] ${path}: only colours change per theme`);
      }
    }
  }
  return { errors, themes, themeNames, base };
}

/* ---- CSS values ------------------------------------------------------ */

const px = (d) => (d.unit === 'rem' ? d.value * 16 : d.value);
const num = (n, d = 4) => String(Number(n.toFixed(d)));
const dimension = (d) => (d.value === 0 ? '0' : `${num(d.value)}${d.unit}`);

/** clamp() with a rem term in the middle: pure vw ignores browser zoom, so text
 *  sized that way fails WCAG 1.4.4 at the widths where it is fluid. */
function fluid(min, max, range = FLUID_RANGE) {
  const [vMin, vMax] = range;
  const slope = (px(max) - px(min)) / (vMax - vMin);
  const intercept = px(min) - slope * vMin;
  return `clamp(${dimension(min)}, ${num(intercept / 16)}rem + ${num(slope * 100)}vw, ${dimension(max)})`;
}

const GENERIC_FAMILIES = new Set(['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-serif', 'ui-sans-serif', 'ui-monospace', 'ui-rounded', 'emoji', 'math', 'fangsong']);
const family = (name) => (GENERIC_FAMILIES.has(name) || /^-/.test(name) ? name : `"${name}"`);

function colorRef(alias, alpha) {
  if (alpha === undefined || alpha === 1) return `var(--${alias.replaceAll('.', '-')})`;
  return `color-mix(in srgb, var(--${alias.replaceAll('.', '-')}) ${num(alpha * 100, 2)}%, transparent)`;
}

/** The CSS for one token in one theme. Aliases stay live as var(). */
export function cssValue(token, entry) {
  const { value, alias } = entry;
  if (alias) {
    if (token.type === 'color') return colorRef(alias, token.ext.alpha);
    return `var(--${alias.replaceAll('.', '-')})`;
  }
  switch (token.type) {
    case 'color':
      return value.css;
    case 'dimension':
      return value.fluidMax ? fluid(value, value.fluidMax, value.fluidRange) : dimension(value);
    case 'duration':
      return `${value.value}${value.unit}`;
    case 'number':
    case 'fontWeight':
      return String(value);
    case 'fontFamily':
      return value.map(family).join(', ');
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    case 'shadow': {
      const layers = Array.isArray(token.raw) ? token.raw : [token.raw];
      return value
        .map((l, i) => {
          const color = l.colorAlias ? colorRef(l.colorAlias) : l.color.css;
          const parts = [dimension(l.offsetX), dimension(l.offsetY), dimension(l.blur), dimension(l.spread), color];
          return (layers[i].inset ? 'inset ' : '') + parts.join(' ');
        })
        .join(', ');
    }
    default:
      return String(value);
  }
}

/** Every declaration, in file order: [name, value] pairs, line-height
 *  companions included, with light-dark() where a colour differs per theme. */
export function declarations(system) {
  const { base, themes, themeNames } = system;
  const out = [];
  for (const [path, token] of base.tokens) {
    let value = cssValue(token, base.resolved.get(path));
    if (themeNames.length === 2 && token.type === 'color') {
      const other = themes[themeNames[1]];
      const otherValue = cssValue(other.tokens.get(path), other.resolved.get(path));
      if (otherValue !== value) value = `light-dark(${value}, ${otherValue})`;
    }
    out.push([token.name, value]);
    const lh = lineHeightOf(path, base);
    if (lh !== undefined) out.push([`${token.name}--line-height`, lh]);
  }
  return out;
}

/** A text size's line height: its own, or the one of the step it aliases. */
function lineHeightOf(path, { tokens }) {
  const token = tokens.get(path);
  if (token.type !== 'dimension') return undefined;
  if (token.ext.lineHeight !== undefined) return String(token.ext.lineHeight);
  const target = aliasOf(token.raw);
  if (target && lineHeightOf(target, { tokens }) !== undefined) return `var(--${tokens.get(target).name}--line-height)`;
  return undefined;
}

/* Reduced motion is honoured once, here, instead of in every component: every
   duration drops to zero and --motion, which every lift multiplies, to 0.
   Overriding transforms per component lost to specificity twice in the
   project this was extracted from. */
function reducedMotion(system) {
  const lines = [];
  for (const token of system.base.tokens.values()) {
    if (token.type === 'duration') lines.push(`--${token.name}: 0ms;`);
  }
  if (system.base.tokens.has('motion')) lines.push('--motion: 0;');
  return lines;
}

function colorScheme(system) {
  if (system.themeNames.length === 1) return ['color-scheme: light;'];
  return ['color-scheme: light dark;'];
}

const indent = (lines, n) => lines.map((l) => ' '.repeat(n) + l).join('\n');

export function renderCss(system) {
  const decls = declarations(system).map(([n, v]) => `--${n}: ${v};`);
  const parts = [
    `/* ${GENERATED_BANNER} */`,
    '@layer theme, base, components, utilities;',
    '',
    '@layer theme {',
    '  :root {',
    indent([...colorScheme(system), ...decls], 4),
    '  }',
  ];
  if (system.themeNames.length === 2) {
    parts.push(
      `  :root[data-theme="light"] { color-scheme: light; }`,
      `  :root[data-theme="${system.themeNames[1]}"] { color-scheme: dark; }`
    );
  }
  parts.push(
    '',
    '  @media (prefers-reduced-motion: reduce) {',
    '    :root {',
    indent(reducedMotion(system), 6),
    '    }',
    '  }',
    '}',
    ''
  );
  return parts.join('\n');
}

/**
 * Tailwind v4. `--color-*: initial` removes Tailwind's own palette, so
 * `bg-red-500` stops existing and every colour utility is a role or a brand
 * step. `static` keeps every variable in the output even when no utility uses
 * it, because the component CSS reads them.
 */
export function renderTailwind(system) {
  const decls = declarations(system).map(([n, v]) => `--${n}: ${v};`);
  const parts = [
    `/* ${GENERATED_BANNER} */`,
    '@theme static {',
    '  --color-*: initial;',
    indent(decls, 2),
    '}',
    '',
    '@layer theme {',
    '  :root {',
    indent(colorScheme(system), 4),
    '  }',
  ];
  if (system.themeNames.length === 2) {
    parts.push(
      `  :root[data-theme="light"] { color-scheme: light; }`,
      `  :root[data-theme="${system.themeNames[1]}"] { color-scheme: dark; }`
    );
  }
  parts.push(
    '  @media (prefers-reduced-motion: reduce) {',
    '    :root {',
    indent(reducedMotion(system), 6),
    '    }',
    '  }',
    '}',
    ''
  );
  return parts.join('\n');
}

/* ---- Claude Design --------------------------------------------------- */

const hexOf = (c) => toHex(c);

/** The list-shaped tokens.json of a Claude Design System. Values are resolved
 *  literals: it reads no var(), no color-mix(), no clamp(). */
export function renderClaudeDesign(system, name) {
  const { base, themes, themeNames } = system;
  const usage = (t) => t.description ?? ROLES[t.path] ?? '';
  const byType = (type) => [...base.tokens.values()].filter((t) => t.type === type);
  const colorTokens = byType('color').map((t) => {
    const value = {};
    for (const theme of themeNames) value[theme] = hexOf(themes[theme].resolved.get(t.path).value);
    return { name: t.name, value: themeNames.length === 1 ? value.light : value, usage: usage(t) };
  });
  const dim = (t) => {
    const v = base.resolved.get(t.path).value;
    const shown = v.fluidMax ?? v;
    return `${num(shown.value)}${shown.unit}`;
  };
  const families = Object.fromEntries(
    byType('fontFamily').map((t) => [t.name.replace(/^font-/, ''), base.resolved.get(t.path).value.map(family).join(', ')])
  );
  const textSizes = byType('dimension').filter((t) => t.path.startsWith('text.'));
  const shadows = byType('shadow').map((t) => ({
    name: t.name,
    value: base.resolved
      .get(t.path)
      .value.map((l) => [l.offsetX, l.offsetY, l.blur, l.spread].map(dimension).join(' ') + ' ' + hexOf(l.color))
      .join(', '),
    usage: usage(t),
  }));
  return JSON.stringify(
    {
      name,
      version: 1,
      meta: { source: `@mickaelbeauregard/design-system (${NS})` },
      color: {
        themes: themeNames.map((id) => ({ id, name: id[0].toUpperCase() + id.slice(1) })),
        tokens: colorTokens,
      },
      type: {
        fonts: [],
        families,
        groups: [
          {
            name: 'Text',
            family: 'body',
            styles: textSizes.map((t) => ({
              name: t.name.replace(/^text-/, ''),
              fontSize: dim(t),
              lineHeight: Number(lineHeightLiteral(t.path, base) ?? 1.5),
            })),
          },
        ],
      },
      spacing: { tokens: byType('dimension').filter((t) => t.path.startsWith('spacing.')).map((t) => ({ name: t.name, value: dim(t), usage: usage(t) })) },
      radius: { tokens: byType('dimension').filter((t) => t.path.startsWith('radius.')).map((t) => ({ name: t.name, value: dim(t), usage: usage(t) })) },
      shadow: { tokens: shadows },
    },
    null,
    2
  ) + '\n';
}

function lineHeightLiteral(path, { tokens }) {
  const token = tokens.get(path);
  if (token.ext.lineHeight !== undefined) return token.ext.lineHeight;
  const target = aliasOf(token.raw);
  return target ? lineHeightLiteral(target, { tokens }) : undefined;
}
